name: Delete old builds

on:
  workflow_dispatch: # 手动运行

permissions:
  contents: read                   # 允许读取仓库内容的权限
  actions: write                   # 允许写入 GitHub Actions 的权限
  id-token: write                  # 允许写入 id-token 的权限（如果需要）

jobs:
  delete_old_builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]  # 使用 Node.js 20 版本
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Delete old builds
      uses: actions/github-script@v5
      with:
        script: |
          const THRESHOLD = 3; // 天数
          const { owner, repo } = context.repo;
          // 获取构建列表
          let response = await github.rest.actions.listWorkflowRuns({
            owner: owner,
            repo: repo,
            status: 'completed',
            per_page: 100, // 可以调整每页显示的构建数量
            page: 1 // 可以调整页码，如果有很多构建的话
          });

          // 遍历构建并删除旧的
          for (let run of response.data.workflow_runs) {
            if (Date.now() - new Date(run.created_at).getTime() > THRESHOLD * 24 * 60 * 60 * 1000) {
              await github.rest.actions.deleteWorkflowRun({
                owner: owner,
                repo: repo,
                run_id: run.id,
              });
            }
          }

          console.log('Old builds deleted successfully.');
